apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: apache-app-deployment 
  labels: 
    app: apache
spec:
  replicas: 3 
  selector:
    matchLabels: 
      app: apache
  template: 
    metadata:
      labels:
        app: apache 
    spec: 
      containers:
        - name: apache-app
          image: sidiclaudio/the-slick-app:v18
          ports:
            - containerPort: 80
